# Nome da Action
name: Snake Game

# Controlador do tempo para atualização automática
on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Faz checkout do repositório
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # Configura autenticação Git para usar o GH_PAT
      - name: Configurar autenticação Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://KleyJkGameDev:${{ secrets.GH_PAT }}@github.com/KleyJkGameDev/KleyJkGameDev.git_
